apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ml-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ml-platform

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mlflow
    targetRevision: "1.4.x"
    helm:
      valueFiles:
        - $values/platform/helm/mlflow/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ml-monitoring    # MLflow tracking server in monitoring ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false   # Namespaces managed separately
      - ServerSideApply=true
